version: '3.8'

services:
  react-app:
    build:
      context: ./react-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./react-app:/app
      - /app/node_modules
    networks:
      - benchmark-network

  preact-app:
    build:
      context: ./preact-app
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./preact-app:/app
      - /app/node_modules
    networks:
      - benchmark-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - react-app
      - preact-app
    networks:
      - benchmark-network

networks:
  benchmark-network:
    driver: bridge
